on:
  push:
    branches:
      - main
      - master
      - development
      - 'releases/**'
  pull_request:
    types: [opened, synchronize, reopened]

name: Main Workflow
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        check-latest: true # Ensure the latest version is used

    - name: Setup environment and verify Java
      run: |
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
        echo "$JAVA_HOME/bin" >> $GITHUB_PATH
        which java
        java -version
        echo "JAVA_HOME=$JAVA_HOME"
        echo "PATH=$PATH"
        # Ensure these directories exist and have correct permissions
        sudo mkdir -p /root/.sonar
        sudo chmod -R 777 /root/.sonar

    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: SonarQube Scanner Action
      uses: philips-software/sonar-scanner-action@v1.5.1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        JAVA_HOME: ${{ env.JAVA_HOME }}/bin:${{ env.PATH }}
      with:
        projectName: edunekta
        projectKey: cipagauta-david_edunekta
        organization: Edunekta
        token: ${{ secrets.SONAR_TOKEN }}
        url: https://sonarcloud.io